version: "3.9"  # optional since v1.27.0
services:
  web:
    build: ../../ui-pickupvb/.
    ports:
      - '8001:80'
    expose:
      - '80'
    links:
      - 'api'
    depends_on:
      - 'api'
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
  nginx:
    build: ../../ui-pickupvb/.
    ports:
      - '8001:80'
    expose:
      - '80'
    links:
      - 'api'
    depends_on:
      - 'api'
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
  api:
    build: ../../api-pickupvb/.
    command: dotnet watch --project ./app run --urls "http://0.0.0.0:80" 
    depends_on:
      - 'db'
    expose:
      - '80'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'vb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'zlock'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'qDLGk#jYP10e'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'aEib6Rg6S#29'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
