version: "3.9"  # optional since v1.27.0
services:
  webserver:
    image: cooler09/ui-pickupvb:0.0.10
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    environment:
      - NGINX_HOST=pickupvb.com
      - NGINX_EMAIL=admin@pickupvb.com
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certs:/etc/letsencrypt
    environment:
      - DOMAINS=pickupvb.com
      - EMAIL=admin@pickupvb.com
    command: certonly --webroot --webroot-path=/etc/letsencrypt -d pickupvb.com --non-interactive --agree-tos --email admin@pickupvb.com
