version: "3.9"  # optional since v1.27.0
services:
  webserver:
    image: cooler09/ui-pickupvb:0.0.10
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    environment:
      - NGINX_HOST=pickupvb.com
      - NGINX_EMAIL=zacharyjordan82@gmail.com
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certs:/etc/letsencrypt
    environment:
      - DOMAINS=pickupvb.com
      - EMAIL=zacharyjordan82@gmail.com
    command: certonly --webroot --webroot-path=/etc/letsencrypt -d pickupvb.com
